import { MigrationInterface, QueryRunner } from "typeorm";

export class Uuid1686372048119 implements MigrationInterface {
    name = 'Uuid1686372048119'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "resetToken" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "resetTokenExpiration" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_94a85bb16d24033a2afdd5df060"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "FK_fe77d226ba9995f4465341080c3"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "FK_84a6e8e5d1f020aa578ddb090ea"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "authorId" uuid`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "FK_77be21a1f5704a0a514b7707d21"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "FK_10d55336d48f555ddad90636658"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_b63950f2876403407137a257a9a"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "PK_94fa9017051b40a71e000a2aff9"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "PK_94fa9017051b40a71e000a2aff9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "commentId" uuid`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "parentReplyId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "parentReplyId" uuid`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "FK_881d775c205c0ffdf10031e5cab"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "FK_c09f4b140fb935fd8ab1cae087c"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "FK_dae8402ae22f4bfa0dcabda3c6c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "FK_71c22350468d699454d3b3227eb"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "FK_518305be2cf8e0b3fcc10cecba9"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "FK_eeeba7592ac40cf39d5f6c4bcfe"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "FK_8c43719f5483d3f2dd1e4d1ef00"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "FK_f5ae21db6cbd444790023e21f8a"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "postId" uuid`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_026bf754be74bd293c9e7774f05"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_881d775c205c0ffdf10031e5cab" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe77d226ba9995f4465341080c"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_881d775c205c0ffdf10031e5cab"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_026bf754be74bd293c9e7774f05" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_026bf754be74bd293c9e7774f05"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_fe77d226ba9995f4465341080c3" PRIMARY KEY ("postId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_881d775c205c0ffdf10031e5ca"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_fe77d226ba9995f4465341080c3"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_026bf754be74bd293c9e7774f05" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_c09f4b140fb935fd8ab1cae087c" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84a6e8e5d1f020aa578ddb090e"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_c09f4b140fb935fd8ab1cae087c"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_84a6e8e5d1f020aa578ddb090ea" PRIMARY KEY ("postId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c09f4b140fb935fd8ab1cae087"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_84a6e8e5d1f020aa578ddb090ea"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_fa52ff554035749a490288b94db"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_518305be2cf8e0b3fcc10cecba9" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77be21a1f5704a0a514b7707d2"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD "replyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_518305be2cf8e0b3fcc10cecba9"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_fa52ff554035749a490288b94db" PRIMARY KEY ("userId", "replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_fa52ff554035749a490288b94db"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_77be21a1f5704a0a514b7707d21" PRIMARY KEY ("replyId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_518305be2cf8e0b3fcc10cecba"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_77be21a1f5704a0a514b7707d21"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_fa52ff554035749a490288b94db" PRIMARY KEY ("replyId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_17e3d163a5d582a5771f71532aa"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_eeeba7592ac40cf39d5f6c4bcfe" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10d55336d48f555ddad9063665"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD "replyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_eeeba7592ac40cf39d5f6c4bcfe"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_17e3d163a5d582a5771f71532aa" PRIMARY KEY ("userId", "replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_17e3d163a5d582a5771f71532aa"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_10d55336d48f555ddad90636658" PRIMARY KEY ("replyId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeeba7592ac40cf39d5f6c4bcf"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_10d55336d48f555ddad90636658"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_17e3d163a5d582a5771f71532aa" PRIMARY KEY ("replyId", "userId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_117637ba11e1aee59c77337feb2"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_dae8402ae22f4bfa0dcabda3c6c" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c43719f5483d3f2dd1e4d1ef0"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD "commentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_dae8402ae22f4bfa0dcabda3c6c"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_117637ba11e1aee59c77337feb2" PRIMARY KEY ("userId", "commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_117637ba11e1aee59c77337feb2"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_8c43719f5483d3f2dd1e4d1ef00" PRIMARY KEY ("commentId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dae8402ae22f4bfa0dcabda3c6"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_8c43719f5483d3f2dd1e4d1ef00"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_117637ba11e1aee59c77337feb2" PRIMARY KEY ("commentId", "userId")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_71c22350468d699454d3b3227eb" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5ae21db6cbd444790023e21f8"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD "commentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_71c22350468d699454d3b3227eb"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c" PRIMARY KEY ("userId", "commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_f5ae21db6cbd444790023e21f8a" PRIMARY KEY ("commentId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71c22350468d699454d3b3227e"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_f5ae21db6cbd444790023e21f8a"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c" PRIMARY KEY ("commentId", "userId")`);
        await queryRunner.query(`CREATE INDEX "IDX_fe77d226ba9995f4465341080c" ON "post_liked_by_user" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_881d775c205c0ffdf10031e5ca" ON "post_liked_by_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_84a6e8e5d1f020aa578ddb090e" ON "post_disliked_by_user" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c09f4b140fb935fd8ab1cae087" ON "post_disliked_by_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77be21a1f5704a0a514b7707d2" ON "reply_liked_by_user" ("replyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_518305be2cf8e0b3fcc10cecba" ON "reply_liked_by_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_10d55336d48f555ddad9063665" ON "reply_disliked_by_user" ("replyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eeeba7592ac40cf39d5f6c4bcf" ON "reply_disliked_by_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c43719f5483d3f2dd1e4d1ef0" ON "comment_liked_by_user" ("commentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dae8402ae22f4bfa0dcabda3c6" ON "comment_liked_by_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5ae21db6cbd444790023e21f8" ON "comment_disliked_by_user" ("commentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_71c22350468d699454d3b3227e" ON "comment_disliked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_b63950f2876403407137a257a9a" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5" FOREIGN KEY ("parentReplyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_94a85bb16d24033a2afdd5df060" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "FK_fe77d226ba9995f4465341080c3" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "FK_881d775c205c0ffdf10031e5cab" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "FK_84a6e8e5d1f020aa578ddb090ea" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "FK_c09f4b140fb935fd8ab1cae087c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "FK_77be21a1f5704a0a514b7707d21" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "FK_518305be2cf8e0b3fcc10cecba9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "FK_10d55336d48f555ddad90636658" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "FK_eeeba7592ac40cf39d5f6c4bcfe" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "FK_8c43719f5483d3f2dd1e4d1ef00" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "FK_dae8402ae22f4bfa0dcabda3c6c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "FK_f5ae21db6cbd444790023e21f8a" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "FK_71c22350468d699454d3b3227eb" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "FK_71c22350468d699454d3b3227eb"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "FK_f5ae21db6cbd444790023e21f8a"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "FK_dae8402ae22f4bfa0dcabda3c6c"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "FK_8c43719f5483d3f2dd1e4d1ef00"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "FK_eeeba7592ac40cf39d5f6c4bcfe"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "FK_10d55336d48f555ddad90636658"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "FK_518305be2cf8e0b3fcc10cecba9"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "FK_77be21a1f5704a0a514b7707d21"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "FK_c09f4b140fb935fd8ab1cae087c"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "FK_84a6e8e5d1f020aa578ddb090ea"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "FK_881d775c205c0ffdf10031e5cab"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "FK_fe77d226ba9995f4465341080c3"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_94a85bb16d24033a2afdd5df060"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_b63950f2876403407137a257a9a"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71c22350468d699454d3b3227e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5ae21db6cbd444790023e21f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dae8402ae22f4bfa0dcabda3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c43719f5483d3f2dd1e4d1ef0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeeba7592ac40cf39d5f6c4bcf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10d55336d48f555ddad9063665"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_518305be2cf8e0b3fcc10cecba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77be21a1f5704a0a514b7707d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c09f4b140fb935fd8ab1cae087"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84a6e8e5d1f020aa578ddb090e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_881d775c205c0ffdf10031e5ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe77d226ba9995f4465341080c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_f5ae21db6cbd444790023e21f8a" PRIMARY KEY ("commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_71c22350468d699454d3b3227e" ON "comment_disliked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_f5ae21db6cbd444790023e21f8a"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c" PRIMARY KEY ("userId", "commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_71c22350468d699454d3b3227eb" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD "commentId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_f5ae21db6cbd444790023e21f8" ON "comment_disliked_by_user" ("commentId") `);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" DROP CONSTRAINT "PK_71c22350468d699454d3b3227eb"`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "PK_05001b8b8a9a6d6a7ba5968a44c" PRIMARY KEY ("commentId", "userId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_117637ba11e1aee59c77337feb2"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_8c43719f5483d3f2dd1e4d1ef00" PRIMARY KEY ("commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_dae8402ae22f4bfa0dcabda3c6" ON "comment_liked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_8c43719f5483d3f2dd1e4d1ef00"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_117637ba11e1aee59c77337feb2" PRIMARY KEY ("userId", "commentId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_117637ba11e1aee59c77337feb2"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_dae8402ae22f4bfa0dcabda3c6c" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD "commentId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8c43719f5483d3f2dd1e4d1ef0" ON "comment_liked_by_user" ("commentId") `);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" DROP CONSTRAINT "PK_dae8402ae22f4bfa0dcabda3c6c"`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "PK_117637ba11e1aee59c77337feb2" PRIMARY KEY ("commentId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_17e3d163a5d582a5771f71532aa"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_10d55336d48f555ddad90636658" PRIMARY KEY ("replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_eeeba7592ac40cf39d5f6c4bcf" ON "reply_disliked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_10d55336d48f555ddad90636658"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_17e3d163a5d582a5771f71532aa" PRIMARY KEY ("userId", "replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_17e3d163a5d582a5771f71532aa"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_eeeba7592ac40cf39d5f6c4bcfe" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD "replyId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_10d55336d48f555ddad9063665" ON "reply_disliked_by_user" ("replyId") `);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" DROP CONSTRAINT "PK_eeeba7592ac40cf39d5f6c4bcfe"`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "PK_17e3d163a5d582a5771f71532aa" PRIMARY KEY ("replyId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_fa52ff554035749a490288b94db"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_77be21a1f5704a0a514b7707d21" PRIMARY KEY ("replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_518305be2cf8e0b3fcc10cecba" ON "reply_liked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_77be21a1f5704a0a514b7707d21"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_fa52ff554035749a490288b94db" PRIMARY KEY ("userId", "replyId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_fa52ff554035749a490288b94db"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_518305be2cf8e0b3fcc10cecba9" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD "replyId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_77be21a1f5704a0a514b7707d2" ON "reply_liked_by_user" ("replyId") `);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" DROP CONSTRAINT "PK_518305be2cf8e0b3fcc10cecba9"`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "PK_fa52ff554035749a490288b94db" PRIMARY KEY ("replyId", "userId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_84a6e8e5d1f020aa578ddb090ea" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c09f4b140fb935fd8ab1cae087" ON "post_disliked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_84a6e8e5d1f020aa578ddb090ea"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_c09f4b140fb935fd8ab1cae087c" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD "postId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_84a6e8e5d1f020aa578ddb090e" ON "post_disliked_by_user" ("postId") `);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" DROP CONSTRAINT "PK_c09f4b140fb935fd8ab1cae087c"`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "PK_9c481ade0d3f6b988d8e9788bbb" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_026bf754be74bd293c9e7774f05"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_fe77d226ba9995f4465341080c3" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_881d775c205c0ffdf10031e5ca" ON "post_liked_by_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_fe77d226ba9995f4465341080c3"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_026bf754be74bd293c9e7774f05" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_026bf754be74bd293c9e7774f05"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_881d775c205c0ffdf10031e5cab" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD "postId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_fe77d226ba9995f4465341080c" ON "post_liked_by_user" ("postId") `);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" DROP CONSTRAINT "PK_881d775c205c0ffdf10031e5cab"`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "PK_026bf754be74bd293c9e7774f05" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "postId" integer`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "comment" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "FK_f5ae21db6cbd444790023e21f8a" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "FK_8c43719f5483d3f2dd1e4d1ef00" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "FK_eeeba7592ac40cf39d5f6c4bcfe" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "FK_518305be2cf8e0b3fcc10cecba9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_disliked_by_user" ADD CONSTRAINT "FK_71c22350468d699454d3b3227eb" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_liked_by_user" ADD CONSTRAINT "FK_dae8402ae22f4bfa0dcabda3c6c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "FK_c09f4b140fb935fd8ab1cae087c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "FK_881d775c205c0ffdf10031e5cab" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "parentReplyId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "parentReplyId" integer`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "commentId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "commentId" integer`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "PK_94fa9017051b40a71e000a2aff9"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "PK_94fa9017051b40a71e000a2aff9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_b63950f2876403407137a257a9a" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_disliked_by_user" ADD CONSTRAINT "FK_10d55336d48f555ddad90636658" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_liked_by_user" ADD CONSTRAINT "FK_77be21a1f5704a0a514b7707d21" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5" FOREIGN KEY ("parentReplyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "authorId" integer`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_disliked_by_user" ADD CONSTRAINT "FK_84a6e8e5d1f020aa578ddb090ea" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_liked_by_user" ADD CONSTRAINT "FK_fe77d226ba9995f4465341080c3" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_94a85bb16d24033a2afdd5df060" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "resetTokenExpiration"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "resetToken"`);
    }

}
