version: '3.3'
services:
  dev-blog-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dockerBlogPost
  test-db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dockerBlogPostTest

#run sql shell - host-192.168.99.100 ,port-5435, password-123